### PR TITLE
Make profile generation a bin-script and hide behind optional feature

### LINKED ISSUE #15: Make calamine dependency optional
Most users will probably use this crate with the packaged profile without setting `FIT_PROFILE` during the build, making the build script a no-op.  But `fitparser` still pulls in the `calamine` dependency.

What do you think about moving the profile generation behind a feature flag and making the `calamine` dependency optional?  This would reduce the dependencies for users of the default profile, and users who want to regenerate the profile would only have to enable that feature.

### PR DESCRIPTION
**Pull request by stadelmanma**
Fixes #15, this removes the build.rs script and instead adds an optional `codegen` feature and a bin script that is hidden behind that feature. This feels a bit more muddy since it's a "development script" that sort of lives in prod dependencies. However unless I missed something it doesn't seem like cargo supports the concept of "optional dev dependencies" or even just development-only scripts.

@robinkrahl do you think this is a suitable fix to avoid pulling calamine at runtime for non-devs? Or is there a better way? I think the cargo docs technically recommended splitting out the stuff into a separate crate and adding it as a dependency which seems equally obnoxious..

### CODE REVIEW

**Comment by robinkrahl** [comment]
Thank you, looks good to me!

> I think the cargo docs technically recommended splitting out the stuff into a separate crate and adding it as a dependency which seems equally obnoxious..

As the update script does not depend on the code of the library, you could also move it into a separate crate that is never published and only used to update the profile.

**Comment by stadelmanma** [comment]
@robinkrahl I did just that and while it seems superfluous, if I'm going to play by the rules it does seem "logically" cleaner than the odd development-only bin script (which I think would be a nice feature for rust/cargo). So all in all I don't hate it as much as expected... Thoughts?

**Comment by robinkrahl** [comment]
Looks good to me!  Did you consider keeping the `fitparser` crate in the repository root and having only the build script in a subdirectory?  I think that would be more intuitive.

**Comment by stadelmanma** [comment]
@robinkrahl I did but I think the clearer separation between the two is good, and it fits neatly into the cargo-workspaces concept.

**Pull request merged**
